name: Create Release

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create pack.zip
      run: |
        zip -r pack.zip .

    - name: Generate SHA1 checksum
      run: |
        sha1sum pack.zip > hash.txt

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Changes in this release:
          - Pack.zip containing all repository contents.
          - Hash.txt containing SHA1 checksum of pack.zip.
        draft: false
        prerelease: false

    - name: Upload pack.zip to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pack.zip
        asset_name: pack.zip
        asset_content_type: application/zip

    - name: Upload hash.txt to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hash.txt
        asset_name: hash.txt
        asset_content_type: text/plain
